r-windows/rtools-packages

mingw-w64-quantlib/PKGBUILD
mingw-w64-quantlib/no-undefined.patch

Quantlib 1.15 

---

mingw-w64-zstd/PKGBUILD

Update PKGBUILD for zstd 1.4.4

---

.github/workflows/main.yml
ci-build.sh
mingw-w64-aws-sdk-cpp/BuildAwsCCommon.patch
mingw-w64-aws-sdk-cpp/BuildAwsChecksums.patch
mingw-w64-aws-sdk-cpp/PKGBUILD
mingw-w64-aws-sdk-cpp/Patch-cmake-submodules.patch
mingw-w64-aws-sdk-cpp/WinHttp-missing-flags.patch
mingw-w64-aws-sdk-cpp/aws-sdk-cpp-pr-1333.patch
mingw-w64-aws-sdk-cpp/vista.patch

Lots of assorted patches from left and right, but it seems to work now.
@eddelbuettel @ihnorton @Shelnutt2 @nealrichardson

Build aws-sdk-cpp

---

mingw-w64-aws-sdk-cpp/PKGBUILD

https://github.com/apache/arrow/commit/1018a4f50fb3cd9b5f622a25ad0c69b1389c9a96 added these as requirements for arrow today

Add identity-management, sts to aws-sdk-cpp

---

mingw-w64-sqlite3/PKGBUILD

See https://github.com/r-spatial/sf/issues/1506

upgrade sqlite and increase column limit

---

mingw-w64-tiledb/PKGBUILD

update tiledb to 2.1.2

---

mingw-w64-tiledb/PKGBUILD

update tiledb to 2.1.3

---

mingw-w64-grpc/PKGBUILD

Add grpc, script from msys2

---

mingw-w64-aom/PKGBUILD
mingw-w64-aom/fix-lib-dest.patch
mingw-w64-libde265/001-fix-VPATH.patch
mingw-w64-libde265/003-fix-pkgconfig-provide-includedir.patch
mingw-w64-libde265/PKGBUILD
mingw-w64-libheif/001-fix-pkgconfig-provide-includedir.patch
mingw-w64-libheif/002-pkg-config-add-dav1d-rav1e.patch
mingw-w64-libheif/PKGBUILD
mingw-w64-x265/PKGBUILD

add heif stack

---

mingw-w64-arrow/PKGBUILD

arrow 3.0.0

---

.github/workflows/main.yml
appveyor.yml
azure-pipelines.yml
ci-build.sh
ci-library.sh
mingw-w64-argtable/PKGBUILD
pacman.conf

Cleanup CI scripts, and test with a package.

Ucrt cleanup

---

.github/workflows/main.yml
mingw-w64-ncurses/001-use-libsystre.patch
mingw-w64-ncurses/002-ncurses-config-win-paths.patch
mingw-w64-ncurses/PKGBUILD

Merge this after all the ucrt rebuilding

update ncurses and enable CI deploy

---

mingw-w64-arrow/PKGBUILD

Testing with rc1 (based off of https://github.com/r-windows/rtools-packages/pull/184 for the 3.0.0 release)

arrow 4.0.0

---

mingw-w64-v8/0000-add-mingw-main-code-changes.patch
mingw-w64-v8/0001-add-mingw-toolchain.patch
mingw-w64-v8/0002-gn-ninja-deletes-objs-workaround.patch
mingw-w64-v8/PKGBUILD
mingw-w64-v8/icu.gn
mingw-w64-v8/v8.pc
mingw-w64-v8/v8_libbase.pc
mingw-w64-v8/v8_libplatform.pc
mingw-w64-v8/zlib.gn

@Kwizatz do you have any guess why GN would segfault in mingw32, but not mingw64? I'm using an older version of mingw and gcc but other than that the same formula as in msys2.

Add mingw-w64-v8

---

mingw-w64-arrow/PKGBUILD

apache-arrow 4.0.1

---

appveyor.yml
mingw-w64-suitesparse/0001-mingw-w64-Use-a-not-lib-as-AR_TARGET-extension.patch
mingw-w64-suitesparse/0002-mingw-w64-Set-SO_OPTS--shared-move-dlls-create-import-libs.patch
mingw-w64-suitesparse/0003-mingw-w64-no-CUDA.patch
mingw-w64-suitesparse/0004-mingw-w64-install-static-libs.patch
mingw-w64-suitesparse/0005-suitesparse-5.8.1-skip-building-Mongoose-GraphBLAS.patch
mingw-w64-suitesparse/0006-suitesparse-5.8.1-fix-mp-link-order.patch
mingw-w64-suitesparse/0007-suitesparse-5.8.1-remove-dependency-on-Metis.patch
mingw-w64-suitesparse/0008-suitesparse-5.8.1-remove-dynamic-libraries-from-make.patch
mingw-w64-suitesparse/PKGBUILD

The suitesparse library is a dependency for a C++ program I am writing an R package wrapper for (rbff: https://github.com/rdinnager/rbff), so I tried to make this Rtools package to help users with installation. I have tested it locally and it works great, and my package compiles fine once it is installed by Rtools. I added two patches to an existing msys2 package mainly to get it to not produce .dlls (see comments in PKGBUILD for more details). Here's hoping it will work on the CI.

added Suitesparse package for sparse matrix algorithms.

---

mingw-w64-geos/PKGBUILD

For https://github.com/r-spatial/sf/issues/1781#issuecomment-916684794

geos 3.9.1

---

ci-build.sh
mingw-w64-pkg-config/PKGBUILD

Matches configuration in r-macos/recipes.

make --static behavior default in pkgconfig

---

mingw-w64-udunits/PKGBUILD

cmake doesn't seem to work anymore :/

udunits 2.2.28

---

ci-build.sh
mingw-w64-libarchive/0001-libarchive-3.6.1-bcrypt-fix.patch
mingw-w64-libarchive/PKGBUILD

The patch is still needed and it applies correctly, with some offsets.

Update libarchive to 3.6.1

---

mingw-w64-libssh2/PKGBUILD

See: https://github.com/libssh2/libssh2/issues/739

Fix some regressions in libssh2

---

mingw-w64-vtk/PKGBUILD

Another update following latest very recent release. Could you please update `rwinlib` as well if all goes well? Thanks!

Update to VTK 9.2.4.

---

mingw-w64-arrow/PKGBUILD

The RC verification isn't done yet but will be finished shortly

apache-arrow 13.0.0
