r-windows/rtools-packages

- ci-build.sh
- mingw-w64-ffmpeg/PKGBUILD
Latest pacman default to new zstd compression: https://github.com/msys2/MSYS2-packages/pull/1824
We want to stick with `.xz` for now for backward compatibility.
> Update ffmpeg 4.2.2 and fix CI to use xz compression

- mingw-w64-openblas/PKGBUILD
Hi, @jeroen. 
OpennBLAS is now up to 0.3.9, and there are some updates for windows (bug fixes, etc..). It took me all day, but I built the package, and then R (by overriding your noconfirms and downgrades) using the scripts and everything finished nicely after 12-14 hours, so I'm hoping you will update the overall repo to use OPB 0.3.9. Thanks!
> Update for OpenBLAS v 0.3.9

- appveyor.yml
- azure-pipelines.yml
- mingw-w64-arrow/PKGBUILD
To get us started, this builds from rc0. 
This also updates the release source URL to use the Apache mirror service, rather than hardcoding a single mirror.
> arrow 0.17.1

- appveyor.yml
- azure-pipelines.yml
- scripts.ps1
Upstream msys2 has currently messed up 2 things at once:
- It switched to `zstd` for msys2-packages but the currently deployed version of pacman on appveyor doesn't support zstd yet. So fails to upgrade itself: https://github.com/msys2/MSYS2-packages/issues/1960
2. The latest installer freezes when upgrading msys2-runtime due to some process locking files: https://github.com/msys2/MSYS2-packages/issues/1965
> Try to fix CI on Azure and AppVeyor

- mingw-w64-libutf8proc/PKGBUILD
- mingw-w64-libutf8proc/libutf8proc.pc.in
Based on the PKGBUILD in MINGW-packages but the shared library build removed.
cc @nealrichardson
> Add PKGBUILD for libutf8proc

- ci-build.sh
- mingw-w64-tiledb/PKGBUILD
- mingw-w64-tiledb/winfixes.patch
This seems to be building. @eddelbuettel @ihnorton @Shelnutt2
@ihnorton can you look if my patch file makes sense, and how we can get these things merged in tiledb? We can go over each of the changes in our call on Friday. In summary:
- Fix some MSVC special casing in cmake files
- Fixed type errors for `OVERLAPPED` and `PathCreateFromUrl` initializers.
- Skip checking for `WIN32_LIBS` (the call to `find_library` doesn't work for 32-bit, plus it is redundant)
- Fix conflict because windows defines an `ERROR` macro in gdi.h so I have renamed that symbol to `ERROR_TILEDB` in the patch. Afaik this doesn't matter because it is not a public header. Alternatively we could try to undef the macro I suppose.
I don't quite understand why tiledb needs curl to build, it doesn't seem to be used in the …
> Add package TileDB

- mingw-w64-ccache/01-directory-separator.patch
- mingw-w64-ccache/PKGBUILD
- readme.md
and document usage for packaging. Will document usage for building R packages in https://github.com/r-windows/docs/blob/master/faq.md#readme.
IIUC the packages will be published to bintray when the PR is merged, so that the installation instructions work then?
Closes #143.
> Provide ccache

- azure-pipelines.yml
- pacman.conf
Merge this when the main MSYS2 mirror http://repo.msys2.org is back online.
> Switch back to main msys2 mirror

- mingw-w64-arrow/PKGBUILD
Changes:
* S3 enabled and aws-sdk-cpp added as a dependency (this will not be added to rtools-backports)
* Mimalloc enabled (the Vista compatibility patch has been released)
* Add some new USE_SHARED=OFF flags
> Update arrow for 2.0.0

- mingw-w64-hiredis/01-cmake-static-libs.patch
- mingw-w64-hiredis/PKGBUILD
This PR adds a new package for [hiredis](https://github.com/redis/hiredis), a lightweight client library for accessing the [redis](https://redis.io/) datastore.
This builds the `libhiredis.a` and `libhiredis_ssl.a` libraries and a test tool `hiredis-test.exe`. However, the testing tool is not currently run as part of the package build process since it requires a locally running redis server (with SSL support since the SSL library has also been built).
This package is intended to support R libraries such as [redux](https://github.com/richfitz/redux) which make use of hiredis.
> Adding new package for hiredis v1.0.0 with SSL support

- mingw-w64-tiledb/PKGBUILD
This upgrades TileDB to 2.1.4 released last Friday.
> tiledb 2.1.4

- mingw-w64-tiledb/PKGBUILD
This upgrades TileDB to the just-released 2.1.5
> tiledb 2.1.5

- mingw-w64-tiledb/PKGBUILD
This updates TileDB to release 2.1.6 made today.
> tiledb 2.1.6

- mingw-w64-rabbitmq-c/0001-librabbitmq-CMakeLists.txt.patch
- mingw-w64-rabbitmq-c/0002-librabbitmq-CMakeLists.txt.patch
- mingw-w64-rabbitmq-c/PKGBUILD
This is intended to support building the [**longears** package](https://github.com/atheriel/longears).
This PR vendors the `PKGBUILD` and patch for rabbitmq-c from MSYS2 upstream commit [`2208191`](https://github.com/msys2/MINGW-packages/commit/22081911686a4c9b37bb3a4364f028f945fdc377). It modifies the `PKGBUILD` to remove the dependency on `popt` (which is only used for the optional tools) and build only the static library (disabling the shared library, tools, examples, and tests, which are irrelevant to R packages that might use it).
In addition, it introduces [a second patch](https://github.com/alanxz/rabbitmq-c/commit/6f7f7932f46018925a95118b1173a9aa8d81a50d) from the unreleased master branch of the original project, which is needed to enable building against `pthreads`. Without this …
> Add rabbitmq-c

- mingw-w64-coinor-cbc/PKGBUILD
This PR updates CBC to version 2.10.5 (as discussed in rwinlib/cbc#1). This PR is based on the latest version of the master branch and (based on previous failed attempts in now closed PRs) passes CI builds/test. I'll cc @ricschuster onto this PR as he originally developed the modified PKGBUILD file. @jeroen, please let me know if there's anything else I can do to help with this PR?
> update cbc to 2.10.5

- mingw-w64-file/0001-file-5.38-mingw-build.patch
- mingw-w64-file/0002-use-libsystre.patch
- mingw-w64-file/PKGBUILD
This add the file (and libmagic) package from mingw. This will become a new requirement for TileDB soon. File is available in [msys2](https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-file) which is where this code comes from.
> Add file package

- mingw-w64-libarchive/PKGBUILD
Looks like archive 3.4.0 has multiple bugs. The checks for the `archive` package crash in 32-bit and are super slow on 64.
> try building an old version

- mingw-w64-tesseract-ocr/PKGBUILD
Fixes https://github.com/ropensci/tesseract/issues/60
Fixes https://github.com/tesseract-ocr/tesseract/issues/3830
> Test upstream tesseract patch to avoid std::regex

- mingw-w64-netcdf/0002-no-file.patch
- mingw-w64-netcdf/PKGBUILD
For version 4.9.0-1 of the netcdf packages in Rtools, the builds and tests completed successfully. However, subsequent manual testing showed that remote opendap URLs were not recognised by `ncdump`.
A closer look at the build logs for netcdf 4.9.0-1 showed that libcurl was not being linked, and this was disabling opendap with only a warning (despite `--enable-dap` being specified for `configure`). To link libcurl statically, the library dependencies need to be passed to `configure` via the `LIBS` variable, and `-DCURL_STATICLIB` must be added to `CPPFLAGS`.
Once libcurl is detected properly, `configure` attempts to find libxml2, before falling back to a bundled ezxml library if libxml2 cannot be used. As libxml2 seems to be preferred, this PR adds libxml2 as a package dependency. Static …
> Enable opendap by properly linking static libcurl

- mingw-w64-arrow/PKGBUILD
Note that because arrow-cpp has bumped up to C++17, we will no longer be able to build the rtools-backports version, only this one.
> arrow 10.0.0
